// Lists every bundled UI language by its own name (endonym) with the English
// name beneath, and applies the chosen one to FBPKeyLanguage. Styled to match the
// main settings screen: a fixed dark panel with a dark-grey card, and an
// FBP-prefixed cell so the OLED sweep leaves its colours alone.

#import "FBPLanguageController.h"
#import "FBPResources.h"
#import "FBPPrefs.h"

static NSString *const kCode = @"code";
static NSString *const kName = @"name";     // endonym
static NSString *const kEng  = @"eng";      // English name

static NSString *const kCell = @"fbp.language.row";

#pragma mark - Cell

/// FBP-prefixed so the OLED sweep leaves its card colour alone.
@interface FBPLanguageCell : UITableViewCell
@end
@implementation FBPLanguageCell
- (instancetype)initWithStyle:(UITableViewCellStyle)style
              reuseIdentifier:(NSString *)reuseIdentifier {
    if ((self = [super initWithStyle:UITableViewCellStyleSubtitle
                     reuseIdentifier:reuseIdentifier])) {
        self.backgroundColor = FBPCardColor();
        self.textLabel.font = FBPFont(16, UIFontWeightRegular);
        self.textLabel.textColor = UIColor.labelColor;   // white under the dark override
        self.detailTextLabel.font = FBPFont(12.5, UIFontWeightRegular);
        self.detailTextLabel.textColor = UIColor.secondaryLabelColor;
        UIView *selected = [[UIView alloc] init];
        selected.backgroundColor = [UIColor colorWithWhite:1.0 alpha:0.06];
        self.selectedBackgroundView = selected;
    }
    return self;
}
@end

#pragma mark - Controller

@interface FBPLanguageController ()
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, NSString *> *> *languages;
@end

@implementation FBPLanguageController

- (instancetype)init {
    if ((self = [super initWithStyle:UITableViewStyleInsetGrouped])) {
        // Endonyms (each shown in its own language), matching the bundled .lproj
        // set generated by test/gen_strings.py. code "" = English/Base.
        _languages = @[
            @{ kCode:@"",        kName:@"English",            kEng:@"English" },
            @{ kCode:@"ar",      kName:@"العربية",            kEng:@"Arabic" },
            @{ kCode:@"bn",      kName:@"বাংলা",              kEng:@"Bengali" },
            @{ kCode:@"de",      kName:@"Deutsch",            kEng:@"German" },
            @{ kCode:@"es",      kName:@"Español",            kEng:@"Spanish" },
            @{ kCode:@"fr",      kName:@"Français",           kEng:@"French" },
            @{ kCode:@"hi",      kName:@"हिन्दी",              kEng:@"Hindi" },
            @{ kCode:@"id",      kName:@"Bahasa Indonesia",   kEng:@"Indonesian" },
            @{ kCode:@"it",      kName:@"Italiano",           kEng:@"Italian" },
            @{ kCode:@"pt-BR",   kName:@"Português (Brasil)", kEng:@"Portuguese (Brazil)" },
            @{ kCode:@"ru",      kName:@"Русский",            kEng:@"Russian" },
            @{ kCode:@"tr",      kName:@"Türkçe",             kEng:@"Turkish" },
            @{ kCode:@"vi",      kName:@"Tiếng Việt",          kEng:@"Vietnamese" },
            @{ kCode:@"ja",      kName:@"日本語",             kEng:@"Japanese" },
            @{ kCode:@"ko",      kName:@"한국어",             kEng:@"Korean" },
            @{ kCode:@"zh-Hans", kName:@"简体中文",           kEng:@"Chinese (Simplified)" },
        ];
    }
    return self;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    self.title = FBPL(@"row.language.title");

    // Fixed dark panel, matching the main settings screen.
    self.overrideUserInterfaceStyle = UIUserInterfaceStyleDark;
    self.view.tintColor = FBPTintColor();
    self.tableView.backgroundColor = FBPPanelColor();
    self.tableView.separatorInset = UIEdgeInsetsMake(0, 16, 0, 0);

    [self.tableView registerClass:FBPLanguageCell.class forCellReuseIdentifier:kCell];
    self.navigationItem.rightBarButtonItem =
        [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemDone
                                                      target:self
                                                      action:@selector(closeTapped)];
    [self applyNavigationChrome];
}

/// A black, opaque navigation bar with a white rounded title.
- (void)applyNavigationChrome {
    UINavigationBar *bar = self.navigationController.navigationBar;
    if (!bar) return;
    self.navigationController.overrideUserInterfaceStyle = UIUserInterfaceStyleDark;
    bar.tintColor = FBPTintColor();
    if (@available(iOS 13.0, *)) {
        UINavigationBarAppearance *appearance = [[UINavigationBarAppearance alloc] init];
        [appearance configureWithOpaqueBackground];
        appearance.backgroundColor = FBPPanelColor();
        appearance.shadowColor = UIColor.clearColor;
        appearance.titleTextAttributes = @{
            NSForegroundColorAttributeName : FBPIconColor(),
            NSFontAttributeName : FBPFont(17, UIFontWeightSemibold),
        };
        bar.standardAppearance = appearance;
        bar.scrollEdgeAppearance = appearance;
        bar.compactAppearance = appearance;
    }
}

- (void)closeTapped {
    [self dismissViewControllerAnimated:YES completion:nil];
}

- (NSString *)currentCode {
    return [FBPPrefs.shared stringForKey:FBPKeyLanguage] ?: @"";
}

#pragma mark - Table

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return 1;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return (NSInteger)self.languages.count;
}

- (UITableViewCell *)tableView:(UITableView *)tableView
         cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    FBPLanguageCell *cell = [tableView dequeueReusableCellWithIdentifier:kCell
                                                           forIndexPath:indexPath];
    NSDictionary *entry = self.languages[indexPath.row];
    cell.textLabel.text = entry[kName];
    cell.detailTextLabel.text = entry[kEng];
    BOOL selected = [entry[kCode] isEqualToString:[self currentCode]];
    cell.accessoryType = selected ? UITableViewCellAccessoryCheckmark
                                  : UITableViewCellAccessoryNone;
    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];

    NSString *code = self.languages[indexPath.row][kCode];
    if ([code isEqualToString:[self currentCode]]) return;

    [FBPPrefs.shared setString:code forKey:FBPKeyLanguage];
    [FBPPrefs.shared commit];

    // Re-localize this screen's own chrome, then refresh the checkmarks. The
    // settings screen behind rebuilds itself in -viewWillAppear on dismissal.
    self.title = FBPL(@"row.language.title");
    [self applyNavigationChrome];
    [tableView reloadData];
}

@end
